package com.buzuriu.dogapp.utils

class BreedsFile {
    companion object {
        var breedsList = listOf<String>(
            "Afghan Hound",
            "Airedale Terrier",
            "Akita",
            "Alaskan Malamute",
            "American Eskimo Dog",
            "American Hairless Terrier",
            "American Staffordshire Terrier",
            "American English Coonhound",
            "Anatolian Shepherd",
            "Australian Cattle Dog",
            "Australian Shepherd",
            "Australian Terrier",
            "Azawakh",
            "Basenji",
            "Basset Hound",
            "Beagle",
            "Bearded Collie",
            "Bedlington Terrier",
            "Belgian Malinois",
            "Belgian Sheepdog",
            "Belgian Tervuren",
            "Bergamasco",
            "Bernese Mountain Dog",
            "Black and Tan Coonhound",
            "Black Russian Terrier",
            "Bloodhound",
            " Bluetick Coonhound",
            "Bolognese",
            "Border Collie",
            "Border Terrier",
            "Borzoi",
            "Boston Terrier",
            "Bouvier des Flandres",
            "Boxer",
            "Boykin Spaniel",
            "Briard",
            "Brittany",
            "Brussels Griffon",
            "Bull Terrier",
            "Bulldog",
            "Bullmastiff",
            "Cairn Terrier",
            "Canaan Dog",
            "Cane Corso",
            "Cardigan Welsh Corgi",
            "Cavalier King Charles Spaniel",
            "Cesky Terrier",
            "Chesapeake Bay Retriever",
            "Chihuahua",
            "Chinese Crested",
            "Chinese Shar-Pei",
            "Chow Chow",
            "Clumber Spaniel",
            "Cocker Spaniel",
            "Collie",
            "Coton de Tulear",
            "Curly - Coated Retriever",
            "Dachshund",
            "Dalmatian",
            "Dandie Dinmont Terrier",
            "Deerhound",
            "Doberman Pinscher",
            "Dogo Argentino",
            "Dogue de Bordeaux",
            "Dutch Shepherd",
            "English Cocker Spaniel",
            "English Foxhound",
            "English Setter",
            "English Springer Spaniel",
            "English Toy Spaniel",
            "Entlebucher Mountain Dog",
            "Eskimo Dog",
            "Estrela Mountain Dog",
            "Field Spaniel",
            "Finnish Lapphund",
            "Finnish Spitz",
            "Flat - Coated Retriever",
            "Fox Terrier",
            "French Bulldog",
            "German Pinscher",
            "German Shepherd Dog",
            "German Shorthaired Pointer",
            "German Wirehaired Pointer",
            "Giant Schnauzer",
            "Glen of Imaal Terrier",
            "Golden Retriever",
            "Gordon Setter",
            "Great Dane",
            "Great Pyrenees",
            "Greater Swiss Mountain Dog",
            "Greyhound",
            "Harrier",
            "Havanese",
            "Ibizan Hound",
            "Icelandic Sheepdog",
            "Irish Red and White Setter",
            "Irish Setter",
            "Irish Terrier",
            "Irish Water Spaniel",
            "Irish Wolfhound",
            "Italian Greyhound",
            "Jack Russell Terrier",
            "Japanese Chin",
            "Keeshond",
            "Kerry Blue Terrier",
            "King Charles Spaniel",
            "Komondor",
            "Kuvasz",
            "Labrador Retriever",
            "Lagotto Romagnolo",
            "Lakeland Terrier",
            "Lancashire Heeler",
            "Leonberger",
            "Lhasa Apso",
            "Lowchen",
            "Maltese",
            "Manchester Terrier",
            "Maremma Sheepdog",
            "Mastiff",
            "Miniature Bull Terrier",
            "Miniature Pinscher",
            "Miniature Schnauzer",
            "Miniature American Shepherd",
            "Neapolitan Mastiff",
            "Newfoundland",
            "Norfolk Terrier",
            "Norwegian Buhund",
            "Norwegian Elkhound",
            "Norwich Terrier",
            "Nova Scotia Duck Tolling Retriever",
            "Old English Sheepdog",
            "Otterhound",
            "Papillon",
            "Parson Russell Terrier",
            "Pekingese",
            "Pembroke Welsh Corgi",
            "Petit Basset Griffon Vendeen",
            "Pharaoh Hound",
            "Plott",
            "Pointer",
            "Polish Lowland Sheepdog",
            "Pomeranian",
            "Poodle",
            "Portuguese Podengo Pequeno",
            "Portuguese Water Dog",
            "Pug",
            "Puli",
            "Pumi",
            "Pyrenean Shepherd",
            "Redbone Coonhound",
            "Rhodesian Ridgeback",
            "Rottweiler",
            "Russell Terrier",
            "Saluki",
            "Samoyed",
            "Schipperke",
            "Scottish Deerhound",
            "Scottish Terrier",
            "Sealyham Terrier",
            "Shetland Sheepdog",
            "Shiba Inu",
            "Shih Tzu",
            "Siberian Husky",
            "Silky Terrier",
            "Skye Terrier",
            "Sloughi",
            "Soft Coated Wheaten Terrier",
            "Spinone Italiano",
            "Staffordshire Bull Terrier",
            "Standard Schnauzer",
            "Sussex Spaniel",
            "Swedish Vallhund",
            "Tibetan Mastiff",
            "Tibetan Spaniel",
            "Tibetan Terrier",
            "Toy Fox Terrier",
            "Vizsla",
            "Weimaraner",
            "Welsh Corgi",
            "Welsh Springer Spaniel",
            "Welsh Terrier",
            "West Highland White Terrier",
            "Whippet",
            "Wire Fox Terrier",
            "Wirehaired Pointing Griffon",
            "Wirehaired Vizsla",
            "Xoloitzcuintli",
            "Yorkshire Terrier"
        )

    }
}